---
title: "Assignment 07"
author: "Analysis of Covariance Using Multiple Regression: Part II"
header-includes:
   - \usepackage{xcolor}
   - \definecolor{umn}{rgb}{0.1843137, 0.4509804, 0.5372549}
output: 
  pdf_document:
    highlight: tango
urlcolor: "umn"
---

In this assignment, you are going to focus on the question of whether there are differences in the average in-state tuition across the five states. Please submit your responses to each of the questions below in a printed document. Also, please adhere to the following guidelines for further formatting your assignment: 

- All graphics should be resized so that they do not take up more room than necessary and should have an appropriate caption and labels. 
- Any typed mathematics (equations, matrices, vectors, etc.) should be appropriately typeset within the document using Equation Editor, Markdown, or \LaTeX. 

This assignment is worth 15 points. Each question is worth one point unless otherwise noted. 

\rule{0.5\linewidth}{\linethickness}

For this assignment, you will use the file *colleges-bordering-mn.csv*. This file contains institutional data for 104 colleges and universities in the five state area (MN, IA, WI, ND, and SD). These data were collected by the Department of Education for the [2013 College Score Card](https://collegescorecard.ed.gov/). The variables are:

- `name`: Name of college/university
- `tuition_in_state`: In-state tuition and fees
- `tuition_out_state`: Out-of-state tuition and fees
- `state`: State postal abbreviation (IA = Iowa, MN = Minnesota, ND = North Dakota, SD = South Dakota, WI = Wisconsin)
- `public`: Is this a public school? (1 = yes, 0 = no)
- `main`: Is this the main campus? (1 = yes, 0 = no)
- `admission`: Admission rate
- `act75`: 75th percentile of the ACT cumulative scores
- `avg_fac_salary`: Average faculty salary (per month)
- `completion`: Four-year completion rate for first-time, full-time students
- `pct_pell`: Percentage of undergraduates who receive a Pell grant

\rule{0.5\linewidth}{\linethickness}


# Preparation: Create Dummy Variables

Create five dummy variables, one for each state, for the analysis.

# Description

1. Create a table of pairwise correlations between average in-state tuition, each of the five state dummy variables, sector (public), 75th-percentile ACT score, and percentage of students on Pell grants.

2. Interpret (i) the correlation between the Minnesota state dummy variable and average in-state tuition, and (ii) the correlation between the Minnesota state dummy variable and the sector (public) variable.

\pagebreak

# Unadjusted Group Differences Model: ANOVA

Fit the regression model that uses the dummy predictors for state to predict variation in average in-state tuition. In this model, use Minnesota as the reference group.

3. Write the fitted regression equation.

4. Are there any statistically reliable differences in the average in-state tuition between Minnesota and its bordering states? Explain.

5. Report and interpret the $R^2$ value for this model.

6. Which group difference(s) is/are not represented in this fitted model?

# Adjusted Group Differences Model: ANCOVA

Again, fit the regression model that uses the dummy predictors for state to predict variation in average in-state tuition, but this time control for differences in (1) sector (public vs. private), (2) ACT scores, and (3) percentage of students on Pell grants. Again, use Minnesota as the reference group.

7. Write the fitted regression equation.

8. Are there any statistically reliable differences in the average in-state tuition between Minnesota and its bordering states after controlling for these other predictors? Explain

9. Report and interpret the $R^2$ value for this model.

# Assumptions

10. Create the density plot of the marginal distribution of the standardized residuals from the ANCOVA model. Add the confidence envelope for the normal distribution. Explain whether or not this plot suggests problems about meeting the normality assumption.

11. Create the scatterplot of the standardized residuals versus the fitted values from the ANCOVA model. In the plot identify observation with extreme residuals ($\leq-3$ or $\geq3$) by indicating  the row number of that observation in the plot.

12. Explain whether or not this plot suggests problems about meeting the linearity and homogeneity of variance assumptions.

\newpage

# Pairwise Differences

13. Create a table (suitable for publication) that presents each of the possible pairwise contrasts (null hypotheses) of interest, the unadjusted _p_-values, and the Benjamini--Hochberg adjusted _p_-values for the controlled differences. (Note: To obtain all of these, you may need to fit additional models.)

14. Based on the Benjamini--Hochberg adjusted _p_-values, which states have a statistically reliable difference in their average in-state tuition after controlling for the other predictors in the model?

15. Create a heatmap of the information that you reported in the table in Question 8. You can see an example of a [heatmap for correlations here](https://developer.ibm.com/predictiveanalytics/wp-content/uploads/sites/48/2011/12/heatmap_corr1.png). We want to create a heatmap that shows the *p*-value for each mean comparison instead of the correlation between variables. So for example, the heatmap we want to create should be a 5x5 grid (the rows and columns would represent states) and the intersecting cells would include the *p*-value for the comparison (rather than the correlation coefficient). Color will be used to indicate the magnitude of the *p*-values. You may want to include different levels of color depending on the degree of significance ($<.05$, $<.01$, etc. At the very least, make sure it is clear whether each comparison is statistically significant or not. Feel free to use any software tool you want to create this heatmap.




