---
title: "Assignment 08"
author: "Interaction Models"
header-includes:
   - \usepackage{xcolor}
   - \definecolor{umn}{HTML}{FF2D21}
   - \usepackage{caption}
   - \captionsetup[table]{textfont={it}, labelfont={}, singlelinecheck=false, labelsep=newline}
   - \captionsetup[figure]{textfont={}, labelfont={it}, singlelinecheck=false, labelsep=period}
   - \usepackage{xfrac}
output: 
  pdf_document:
    highlight: tango
    latex_engine: xelatex
    fig_width: 6
    fig_height: 6
mainfont: "Sabon"
sansfont: "Helvetica Neue UltraLight"
monofont: Inconsolata
urlcolor: "umn"
always_allow_html: yes
---

\frenchspacing

This assignment is intended to give you more experience fitting and interpreting regression models with categorical predictors. Submit your responses to each of the questions below in a printed document. All graphics should be resized so that they do not take up more room than necessary and also should have an appropriate caption. This assignment is worth 16 points. (Each question is worth 1 point unless otherwise noted.)

For this assignment, you will examine whether there are differences in average in-state tuition between Minnesota and its bordering states. To do so, you will use the file *colleges-bordering-mn.csv* (see the [data codebook](http://zief0002.github.io/epsy-8251/codebooks/colleges-bordering-mn.html)).


# Preparation: Fitting Models

Fit the following regression models. For all models, use the average in-state tuition as the response variable. You will use the output from the fitted models to answer the questions in the assignment.

- **Model 1:** Main effects of educational sector, 75th-percentile ACT score, and admission rate. 
- **Model 2:** Main effects of educational sector, 75th-percentile ACT score, and admission rate; and an interaction effect between educational sector and 75th-percentile ACT score
- **Model 3:** Main effects of educational sector, 75th-percentile ACT score, and admission rate; and an interaction effect between educational sector and admission rate
- **Model 4:** Main effects of educational sector, 75th-percentile ACT score, and admission rate; and an interaction effect between admission rate and 75th-percentile ACT score


# Description

1. Create a table of pairwise correlations between average in-state tuition, sector (public), 75th-percentile ACT score, and admission rate.

2. Based on the correlation table, can you infer whether or not there will be an interaction between between 75th-percentile ACT score and admission rate in the sample? Explain.

# Table of Regression Results

3. Examine the structure and formatting of Table 9 at http://zief0002.github.io/epsy-8251/misc/creating-tables/creating-tables.html. Mimic the format and structure of this table to create a table to present the numerical information from the four models you fitted in this assignment. Make sure the table you create also has an appropriate caption. If the table is too wide, change the page orientation in your word processing program to ``Landscape'', rather than changing the size of the font. **(2pts.)**

\newpage

# Model 2

4. Write the fitted regression equation for Model 2.

5. Based on the inferential results from fitting this model, is there an interaction effect between educational sector and 75th-percentile ACT scores? Explain.

6. Interpret the coefficient associated with the interaction effect between educational sector and 75th-percentile ACT scores.

7. Create a plot of the fitted model showing the pertinent results from Model 2. Be sure to appropriately differentiate between lines that you include in the plot (e.g., do not differentiate by color unless you plan to print in color). Include the plot in your word-processed document. 

# Model 3

8. Write the fitted regression equation for Model 3.

9. Based on the inferential results from fitting this model, is there an interaction effect between educational sector and admission rate? Explain.

10. Interpret the coefficient associated with the interaction effect between educational sector and admission rate.

11. Re-write the fitted regression equation, by writing two fitted equations: one for public schools and one for private schools. Be sure each equation is identified with the appropriate subgroup.

# Model 4

12. Write the fitted regression equation for Model 4.

13. Based on the inferential results from fitting this model, is there an interaction effect between 75th-percentile ACT score and admission rate? Explain.

14. Create a plot of the fitted model that allows you to interpret the interaction between ACT score and admission rate. Be sure to appropriately differentiate between lines that you include in the plot (e.g., do not differentiate by color unless you plan to print in color). Include the plot in your word-processed document.

15. Using the plot you just created, interpret the interaction effect between 75th-percentile ACT score and admission rate. 
