# Schedule

Below is the tenative schedule for the class. The dates are subject to change at the instructor's discretion. Readings should be completed prior to class.

<br />

## Calendar

<br />

<table class="table">

<thead>
<tr>
<th style="width:10%;text-align:center"></th>
<th style="width:10%;">T/R</th>
<th style="width:10%;">M/W</th>
<th style="width:10%;text-align:center">Reading</th>
<th style="width:40%;">Topic</th>
<th style="width:10%;text-align:center">Notes</th>
<th style="width:10%;text-align:center">Script</th>
</tr>
</thead>

<tbody>

<!-- Unit 00: Welcome -->

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Sept. 03</td>
<td>Sept. 04</td>
<td align="center" style="vertical-align:middle;">
  <a href="preparation.html#welcome">
    <span class="fa fa-book" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td>Welcome to EPsy 8251</td>
<td align="center" style="vertical-align:middle;">
  <span class="fa fa-file-pdf" style="color: #f1f1f1; font-size: 20px;"></span>
</td>
<td align="center" style="vertical-align:middle;">
  <span class="fab fa-r-project" style="color: #f1f1f1; font-size: 20px;"></span>
</td>
</tr>


<!-- Unit 01: Introduction to Statistical Computing -->

<tr>
<td colspan="7"><b>Unit 01: Introduction to Statistical Computing</b></td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Sept. 05</td>
<td>Sept. 09</td>
<td align="center" style="vertical-align:middle;">
  <a href="preparation.html#rstudio">
    <span class="fa fa-book" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td>Introduction to R and RStudio</td>
<td align="center" style="vertical-align:middle;">
  <a href="http://zief0002.github.io/epsy-8251/misc/01-introduction-to-r.html">
    <span class="fas fa-link" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td align="center" style="vertical-align:middle;">
  <span class="fab fa-r-project" style="color: #f1f1f1; font-size: 20px;"></span>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Sept. 10</td>
<td>Sept. 11</td>
<td align="center" style="vertical-align:middle;">
  <a href="preparation.html#dplyr">
    <span class="fa fa-book" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td>Data Wrangling with dplyr</td>
<td align="center" style="vertical-align:middle;">
  <a href="http://zief0002.github.io/epsy-8251/misc/02-data-wrangling-with-dplyr.html">
    <span class="fas fa-link" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td align="center" style="vertical-align:middle;">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/scripts/02-data-wrangling-with-dplyr.R">
    <span class="fab fa-r-project" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Sept. 12</td>
<td>Sept. 16</td>
<td align="center" style="vertical-align:middle;">
  <a href="preparation.html#ggplot">
    <span class="fa fa-book" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td>Plotting with ggplot2</td>
<td align="center" style="vertical-align:middle;">
  <a href="http://zief0002.github.io/epsy-8251/misc/03-plotting-with-ggplot2.html">
    <span class="fas fa-link" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td align="center" style="vertical-align:middle;">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/scripts/03-plotting-with-ggplot2.R">
    <span class="fab fa-r-project" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
</tr>


<!-- Unit 02: Introduction to Linear Regression -->

<tr>
<td colspan="7"><b>Unit 02: Introduction to Linear Regression</b></td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Sept. 17</td>
<td>Sept. 18</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="preparation.html#ols-description">
    <span class="fa fa-book" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td style="vertical-align:middle;" rowspan="2">Simple Linear Regression: Description<br />
  <span style="margin-left:5px; color:#5a067d;font-size:12px;">*[Notes and script file updated 09-24-2019]*</span></td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/notes/04-simple-regression-description.pdf">
    <span class="fa fa-file-pdf" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/scripts/04-simple-regression-description.R">
    <span class="fab fa-r-project" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Sept. 19</td>
<td>Sept. 23</td>
</tr>

<!-- LEAST SQUARES ESTIMATION -->

<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Sept. 24</td>
<td>Sept. 25</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <span class="fa fa-book" style="color: #f1f1f1; font-size: 20px;"></span>
</td>
<td style="vertical-align:middle;" rowspan="2">Least Squares Estimation<br />
  <span style="margin-left:5px; color:#5a067d;font-size:12px;">*[Notes and Script file updated 09-24-2019]*</span></td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/notes/05-least-squares-estimation.pdf">
    <span class="fa fa-file-pdf" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/scripts/05-least-squares-estimation.R">
    <span class="fab fa-r-project" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Sept. 26</td>
<td>Sept. 30</td>
</tr>

<!-- CORRELATION & STANDARDIZED REGRESSION -->

<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Sept. 26</td>
<td>Sept. 30</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="preparation.html#coefinf">
    <span class="fa fa-book" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td style="vertical-align:middle;" rowspan="2">Correlation and Standardized Regression</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/notes/06-correlation.pdf">
    <span class="fa fa-file-pdf" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/scripts/06-correlation.R">
    <span class="fab fa-r-project" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Oct. 01</td>
<td>Oct. 02</td>
</tr>



<!-- Unit 03: Statistical Uncertainty and Inference -->

<tr>
<td colspan="7"><b>Unit 04: Statistical Uncertainty and Inference</b></td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Oct. 03</td>
<td>Oct. 07</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="preparation.html#coefinf">
    <span class="fa fa-book" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td style="vertical-align:middle;" rowspan="2">Coefficient-Level Inference</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/notes/07-coefficient-level-inference.pdf">
    <span class="fa fa-file-pdf" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/scripts/07-coefficient-level-inference.R">
    <span class="fab fa-r-project" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Oct. 08</td>
<td>Oct. 09</td>
</tr>


<!-- MODEL-LEVEL INFERENCE -->


<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Oct. 10</td>
<td>Oct. 14</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <span class="fa fa-book" style="color: #f1f1f1; font-size: 20px;"></span>
</td>
<td style="vertical-align:middle;" rowspan="2">Model-Level Inference</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/notes/08-model-level-inference.pdf">
    <span class="fa fa-file-pdf" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/scripts/08-model-level-inference.R">
    <span class="fab fa-r-project" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Oct. 15</td>
<td>Oct. 26</td>
</tr>


<!-- Unit 04: Multiple Linear Regression and Statistical Control -->


<tr>
<td colspan="7"><b>Unit 04: Multiple Linear Regression and Statistical Control</b></td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Oct. 17</td>
<td>Oct. 21</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="preparation.html#multreg">
    <span class="fa fa-book" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td style="vertical-align:middle;" rowspan="2">Introduction to Multiple Linear Regression</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/notes/09-introduction-to-multiple-regression.pdf">
    <span class="fa fa-file-pdf" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/scripts/09-introduction-to-multiple-regression.R">
    <span class="fab fa-r-project" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Oct. 22</td>
<td>Oct. 23</td>
</tr>

<!-- UNDERSTANDING STATISTICAL CONTROL -->

<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Oct. 24</td>
<td>Oct. 28</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <span class="fa fa-book" style="color: #f1f1f1; font-size: 20px;"></span>
</td>
<td style="vertical-align:middle;" rowspan="2">Understanding Statistical Control</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/notes/10-understanding-statistical-control.pdf">
    <span class="fa fa-file-pdf" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/scripts/10-understanding-statistical-control.R">
    <span class="fab fa-r-project" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Oct. 29</td>
<td>Oct. 30</td>
</tr>



<!-- Unit 05: Model Assumptions -->

<tr>
<td colspan="7"><b>Unit 05: Model Assumptions</b></td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Oct. 31</td>
<td>Nov. 04</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="preparation.html#assump">
    <span class="fa fa-book" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td style="vertical-align:middle;" rowspan="2">Assumptions of the Regression Model</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/notes/11-assumptions-of-the-regression-model.pdf">
    <span class="fa fa-file-pdf" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/scripts/11-assumptions-of-the-regression-model.R">
    <span class="fab fa-r-project" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Nov. 05</td>
<td>Nov. 06</td>
</tr>


<!-- Unit 06: Categorical Predictors -->

<tr>
<td colspan="7"><b>Unit 06: Categorical Predictors</b></td>
</tr>


<!-- CODING A CATEGORICAL PREDICTOR -->

<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Nov. 07</td>
<td>Nov. 11</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="preparation.html#dummy">
    <span class="fa fa-book" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td style="vertical-align:middle;" rowspan="2">Dummy Coding Categorical Predictors</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/notes/12-dummy-coding-categorical-predictors.pdf">
    <span class="fa fa-file-pdf" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/scripts/12-dummy-coding-categorical-predictors.R">
    <span class="fab fa-r-project" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Nov. 12</td>
<td>Nov. 13</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Nov. 14</td>
<td>Nov. 18</td>
<td align="center" style="vertical-align:middle;">
  <a href="preparation.html#effect">
    <span class="fa fa-book" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td style="vertical-align:middle;">Effects Coding Categorical Predictors</td>
<td align="center" style="vertical-align:middle;">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/notes/13-effects-coding-categorical-predictors.pdf">
    <span class="fa fa-file-pdf" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td align="center" style="vertical-align:middle;">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/scripts/13-effects-coding-categorical-predictors.R">
    <span class="fab fa-r-project" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Nov. 19</td>
<td>Nov. 20</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="preparation.html#poly">
    <span class="fa fa-book" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td style="vertical-align:middle;" rowspan="2">Polychotomous Categorical Predictors</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/notes/14-polychotomous-categorical-predictors.pdf">
    <span class="fa fa-file-pdf" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/scripts/14-polychotomous-categorical-predictors.R">
    <span class="fab fa-r-project" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Nov. 21</td>
<td>Nov. 25</td>
</tr>


<!-- Unit 07: Interaction Models -->

<tr>
<td colspan="7"><b>Unit 07: Interaction Models</b></td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Nov. 26</td>
<td>Dec. 02</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="preparation.html#intmodel">
    <span class="fa fa-book" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td style="vertical-align:middle;" rowspan="2">Introduction to Interaction Models</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/notes/15-introduction-to-interaction-models.pdf">
    <span class="fa fa-file-pdf" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/scripts/15-introduction-to-interaction-models.R">
    <span class="fab fa-r-project" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Dec. 03</td>
<td>Dec. 04</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Dec. 09</td>
<td>Dec. 10</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="preparation.html#intmodel">
    <span class="fa fa-book" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td style="vertical-align:middle;" rowspan="2">More Interaction Models</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/notes/16-more-interaction-models.pdf">
    <span class="fa fa-file-pdf" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  <a href="https://github.com/zief0002/epsy-8251/raw/master/scripts/16-more-interaction-models.R">
    <span class="fab fa-r-project" style="color: #ff2600; font-size: 20px;"></span>
  </a>
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Dec. 11</td>
<td> </td>
</tr>

</tbody>
</table>    

